# action.yml
name: 'GitInspector Action'
description: 'Clones the repo and runs inspector outputing to the html folder'
inputs:
  repo:  # id of input
    description: 'Repo to test'
    required: true
    default: 'letheanVPN/blockchain-iTw3'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
